// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiddleWareApi.Data;

#nullable disable

namespace MiddleWareApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240828081920_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiddleWareApi.Data.MiddleWare", b =>
                {
                    b.Property<int>("MiddleWareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MiddleWareId"));

                    b.Property<string>("MiddleWareDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleWareName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MiddleWareId");

                    b.ToTable("middleWares");
                });
#pragma warning restore 612, 618
        }
    }
}
